<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-21T20:40:45 IST" name="HRMtestNG" finished-at="2023-03-21T20:40:55 IST" duration-ms="10518">
    <groups>
      <group name="logo">
        <method signature="LoginPageFunctionaltyTest.testlogo1Display()[pri:4, instance:com.loginPageTest.LoginPageFunctionaltyTest@1de5f259]" name="testlogo1Display" class="com.loginPageTest.LoginPageFunctionaltyTest"/>
        <method signature="LoginPageFunctionaltyTest.testlogo2Display()[pri:5, instance:com.loginPageTest.LoginPageFunctionaltyTest@1de5f259]" name="testlogo2Display" class="com.loginPageTest.LoginPageFunctionaltyTest"/>
      </group> <!-- logo -->
      <group name="setup">
        <method signature="LoginPageFunctionaltyTest.setup()[pri:1, instance:com.loginPageTest.LoginPageFunctionaltyTest@1de5f259]" name="setup" class="com.loginPageTest.LoginPageFunctionaltyTest"/>
      </group> <!-- setup -->
      <group name="title">
        <method signature="LoginPageFunctionaltyTest.testTitle()[pri:2, instance:com.loginPageTest.LoginPageFunctionaltyTest@1de5f259]" name="testTitle" class="com.loginPageTest.LoginPageFunctionaltyTest"/>
      </group> <!-- title -->
      <group name="URL">
        <method signature="LoginPageFunctionaltyTest.testURL()[pri:3, instance:com.loginPageTest.LoginPageFunctionaltyTest@1de5f259]" name="testURL" class="com.loginPageTest.LoginPageFunctionaltyTest"/>
      </group> <!-- URL -->
    </groups>
    <test started-at="2023-03-21T20:40:45 IST" name="TestloginPage" finished-at="2023-03-21T20:40:55 IST" duration-ms="10518">
      <class name="com.loginPageTest.LoginPageFunctionaltyTest">
        <test-method signature="setup()[pri:1, instance:com.loginPageTest.LoginPageFunctionaltyTest@1de5f259]" started-at="2023-03-21T20:40:45 IST" name="setup" finished-at="2023-03-21T20:40:52 IST" duration-ms="7161" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testTitle()[pri:2, instance:com.loginPageTest.LoginPageFunctionaltyTest@1de5f259]" started-at="2023-03-21T20:40:52 IST" name="testTitle" depends-on-groups="setup" finished-at="2023-03-21T20:40:53 IST" duration-ms="79" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTitle -->
        <test-method signature="testURL()[pri:3, instance:com.loginPageTest.LoginPageFunctionaltyTest@1de5f259]" started-at="2023-03-21T20:40:53 IST" name="testURL" depends-on-groups="setup, title" finished-at="2023-03-21T20:40:53 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testURL -->
        <test-method signature="testlogo1Display()[pri:4, instance:com.loginPageTest.LoginPageFunctionaltyTest@1de5f259]" started-at="2023-03-21T20:40:53 IST" name="testlogo1Display" finished-at="2023-03-21T20:40:53 IST" duration-ms="98" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertFalse(Assert.java:78)
at org.testng.Assert.assertFalse(Assert.java:88)
at com.loginPageTest.LoginPageFunctionaltyTest.testlogo1Display(LoginPageFunctionaltyTest.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testlogo1Display -->
        <test-method signature="testlogo2Display()[pri:5, instance:com.loginPageTest.LoginPageFunctionaltyTest@1de5f259]" started-at="2023-03-21T20:40:53 IST" name="testlogo2Display" finished-at="2023-03-21T20:40:53 IST" duration-ms="71" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertFalse(Assert.java:78)
at org.testng.Assert.assertFalse(Assert.java:88)
at com.loginPageTest.LoginPageFunctionaltyTest.testlogo2Display(LoginPageFunctionaltyTest.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testlogo2Display -->
        <test-method signature="testLoginFunctionality()[pri:6, instance:com.loginPageTest.LoginPageFunctionaltyTest@1de5f259]" started-at="2023-03-21T20:40:53 IST" name="testLoginFunctionality" depends-on-groups="setup, title, URL" finished-at="2023-03-21T20:40:55 IST" duration-ms="1566" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginFunctionality -->
      </class> <!-- com.loginPageTest.LoginPageFunctionaltyTest -->
    </test> <!-- TestloginPage -->
  </suite> <!-- HRMtestNG -->
</testng-results>
